- name: loops
  hosts: localhost
  tasks:
  - name: print persons
    ansible.builtin.package:
      name: "{{item}}"
      state: present # item is a default keyword
    loop:
    - mysql
    - git
    - postfix
    